### ISSUE TITLE
v0.0.3 is a large .gem

### ISSUE THREAD

**Issue by domcleal** [theforeman/foreman_remote_execution#24]
Note that one of your releases, v0.0.3 is very large (7MB): https://rubygems.org/gems/foreman_remote_execution/versions

    7.3M    doc/tmp/images/plantuml/

Perhaps use `git ls-files` in your gemspec so that only version tracked files are included in the release instead of whatever's in the working directory, as this dir is gitignored.

**Comment by stbenjam** [comment]
Oh thanks, my fault, I had built the docs when I was testing.

**Comment by stbenjam** [comment]
Moved to redmine http://projects.theforeman.org/issues/12125
